### ISSUE TITLE
tty.js should be started automatically if one was not found

### ISSUE THREAD

**Issue by dbkaplun** [artoale/brackets-terminal#5]

**Comment by brad-jones** [comment]
I moved from Sublime to Atom and now I am using Brackets.
I wish I could get the best bits of all 3 and squish them all together.

Anyway while I'm sure you have given this plenty of thought.
In the case you haven't seen this atom plugin: https://github.com/webBoxio/atom-term2
It might provide some ideas on how to auto start tty.js as they manage to do it.

But otherwise good job on extension.

**Comment by brad-jones** [comment]
Also for anyone else looking for super quick solution I just modded my brackets start script.

```bash
#!/bin/bash
#
# Copyright (c) 2011 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Start tty.js
/usr/bin/tty.js --daemonize

# Let the wrapped binary know that it has been run through the wrapper.
export CHROME_WRAPPER="`readlink -f "$0"`"

HERE="`dirname "$CHROME_WRAPPER"`"

# This also makes RPMs find the compatibly-named library symlinks.
if [[ -n "$LD_LIBRARY_PATH" ]]; then
  LD_LIBRARY_PATH="$HERE:$HERE/lib:$LD_LIBRARY_PATH"
else
  LD_LIBRARY_PATH="$HERE:$HERE/lib"
fi
export LD_LIBRARY_PATH

exec -a "$0" "$HERE/Brackets"  "$@"
```

You could probably then kill the process with the ```window.onbeforeunload``` event.
But I haven't bothered looking into that further.

**Comment by CupOfTea696** [comment]
@brad-jones Which file is that?

**Comment by brad-jones** [comment]
On a Linux system its the main start script.
Probably ```/opt/brackets/brackets```
